spring:
  application:
    name: zipkin
  rabbitmq:
    host: woodpecker.rmq.cloudamqp.com
    port: 5672
    username: kdmffedc
    password: ENC(CsUZ58Eb0zuABi41WRxVEXYgaqYIwxFMLJMYQRXzBQAL/Koi08Njxv80yHZgJdqR)
    virtual-host: kdmffedc

server:
  port: ${PORT:9411}

security:
  user:
    name: admin
    password: ${ZIPKIN_SERVER_PASSWORD:admin}

jasypt:
  encryptor:
    password: jazaradebuggers