spring:
  application:
    name: zipkin
  rabbitmq:
    host: woodpecker.rmq.cloudamqp.com
    port: 5672
    username: kdmffedc
    password: 2-W4eKdkrc0nUY4x12OjUFQC5_akBHwG
    virtual-host: kdmffedc

server:
  port: 9411

security:
  user:
    name: admin
    password: ${ZIPKIN_SERVER_PASSWORD:admin}
